# Generated by Django 5.0 on 2024-01-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_alter_anish_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anish',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
