# Generated by Django 5.0 on 2024-02-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='lastname',
            new_name='LastName',
        ),
    ]
